In [1]:
import pandas as pd
import numpy as np

In [2]:
# dib = pd.read_csv('Diabetes+Example+Data.csv')
dib = pd.read_csv('churn_data.csv')

In [3]:
dib.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
# Converting Yes to 1 and No to 0
dib['Churn'] = dib['Churn'].map({'Yes': 0, 'No': 1})

In [5]:
dib.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,1
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,1
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,0
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,1
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,0

In [6]:
variables_in_x = ['customerID','tenure','PhoneService','Contract','PaperlessBilling','PaymentMethod','MonthlyCharges','TotalCharges']
# Putting feature variable to X
X = dib[variables_in_x]

# Putting response variable to y
y = dib['Churn']

In [7]:
help(dib.drop)

Help on method drop in module pandas.core.frame:

drop(labels: 'IndexLabel | None' = None, *, axis: 'Axis' = 0, index: 'IndexLabel | None' = None, columns: 'IndexLabel | None' = None, level: 'Level | None' = None, inplace: 'bool' = False, errors: 'IgnoreRaise' = 'raise') -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Drop specified labels from rows or columns.

    Remove rows or columns by specifying label names and corresponding
    axis, or by directly specifying index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the :ref:`user guide <advanced.shown_levels>`
    for more information about the now unused levels.

    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as a list-like.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or list-like
        Alternative to specifying axis (``labels, axis=0``
        is equivalent to ``index=labels``).
    columns : single label or list-like
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False
        If False, return a copy. Otherwise, do operation
        in place and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    DataFrame or None
        Returns DataFrame or None DataFrame with the specified
        index or column labels removed or None if inplace=True.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis.

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3, 4),
    ...                   columns=['A', 'B', 'C', 'D'])
    >>> df
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(['B', 'C'], axis=1)
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=['B', 'C'])
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(levels=[['llama', 'cow', 'falcon'],
    ...                              ['speed', 'weight', 'length']],
    ...                      codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
    ...                             [0, 1, 2, 0, 1, 2, 0, 1, 2]])
    >>> df = pd.DataFrame(index=midx, columns=['big', 'small'],
    ...                   data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
    ...                         [250, 150], [1.5, 0.8], [320, 250],
    ...                         [1, 0.8], [0.3, 0.2]])
    >>> df
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    Drop a specific index combination from the MultiIndex
    DataFrame, i.e., drop the combination ``'falcon'`` and
    ``'weight'``, which deletes only the corresponding row

    >>> df.drop(index=('falcon', 'weight'))
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            length  0.3     0.2

    >>> df.drop(index='cow', columns='small')
                    big
    llama   speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index='length', level=1)
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

In [8]:
dib.head(5)

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,1
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,1
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,0
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,1
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,0

In [9]:

# Creating a dummy variable for some of the categorical variables and dropping the first one.
dummy1 = pd.get_dummies(dib[['Contract', 'PaymentMethod']], drop_first=True)

# Adding the results to the master dataframe
dib = pd.concat([dib, dummy1], axis=1)


# List of variables to map

# varlist =  ['PhoneService', 'PaperlessBilling','PaymentMethod_Credit card (automatic)','PaymentMethod_Electronic check','PaymentMethod_Mailed check','Contract_One year','Contract_Two year']
varlist =  ['PhoneService', 'PaperlessBilling']


# Defining the map function
def binary_map(x):
    return x.map({'Yes': 1, "No": 0})

# Applying the function to the housing list
dib[varlist] = dib[varlist].apply(binary_map)

varlist =  ['PaymentMethod_Credit card(automatic)','PaymentMethod_Electroniccheck','PaymentMethod_Mailedcheck','Contract_Oneyear','Contract_Twoyear']

# Defining the map function
def convert_bool_to_int(x):
    return x.map({False:0, True: 1})

dib[varlist].apply(convert_bool_to_int)

dib.drop(columns=['PaymentMethod','Contract','customerID'])
# dib.drop('Contract')
# dib.drop('customerID')

KeyError: "None of [Index(['PaymentMethod_Credit card(automatic)', 'PaymentMethod_Electroniccheck',\n       'PaymentMethod_Mailedcheck', 'Contract_Oneyear', 'Contract_Twoyear'],\n      dtype='object')] are in the [columns]"

In [ ]:
dib.head(5)

In [ ]:
import statsmodels.api as sm

In [ ]:
logm1 = sm.GLM(y,(sm.add_constant(X)), family = sm.families.Binomial())
logm1.fit().summary()